---
title: "Labs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

| Week | Topic  |  Lab  |  Homework |  Key  |
|--|----------|:-------------:|:------:|:------:|
| 0 | Review of basic matrix math in R |  [Matrix Math in R](Labs/Week 0 basic matrix/basic-matrix-math.pdf) |  Questions are at the end of the lab | [Key](Labs/Week 0 basic matrix/basic-matrix-math-key.pdf) |
| 1 | Linear regression in matrix form |  [Lab 1 Linear regression](Labs/Week 1 linear regression/Lab 1 Linear Regression in Matrix Form.pdf) | Questions are at the end of the lab | [Key](Labs/Week 1 linear regression/Homework-Key-Linear-Regression.pdf) |
| 2 | Time series functions in R |  [Lab 2 ts functions](Labs/Week 2 intro to ts/intro-ts-funcs.pdf)<br/>[CO2_data.csv](Labs/Week 2 intro to ts/CO2_data.csv) | Questions are at the end of the lab | [Key](Labs/Week 2 intro to ts/HW2_answer_key_pdf.pdf) |
| 3 | Fitting univariate state-space models |  [Lab 3 uni ss](Labs/Week 3 fitting uni ss models/fitting-univariate-state-space.pdf)<br />[MARSS Quick Start Guide](Files/Quick_Start.pdf) | Questions are at the end of the lab | [Key](Labs/Week 3 fitting uni ss models/fitting-univariate-ss-key.pdf) |
| 3 | Intro to JAGS |  [Lab 3 JAGS](Labs/Week 3 intro to jags/intro-to-jags.pdf)<br/>[fitting w JAGs example code](Labs/Week 3 fitting uni ss models/Fitting univariate state-space models in JAGS.R)<br/>[fitting w STAN example code](Labs/Week 3 Stan code/ss_ar_mean.stan)| |  |
| 4 | Fitting multivariate state-space models |  [Lab 4 MARSS](Labs/Week 4 fitting multi ss models/multivariate-ss.pdf)<br/>[Lab 4 MARSS w covariates](Labs/Week 4 fitting multi ss models/multivariate-ss-with-cov.pdf)<br />[MARSS Quick Start Guide](Files/Quick_Start.pdf)| [Homework 4](Labs/Week 4 fitting multi ss models/Homework-4.pdf) | [Key](Labs/Week 4 fitting multi ss models/multivariate-ss-with-cov-hw-key.pdf) |
| 5 | Fitting Dynamic Linear Models |  [Lab 5 DLM](Labs/Week 5 fitting DLMs/DLM_lab_5.pdf)<br/>[KvichakSockey.RData](Labs/Week 5 fitting DLMs/KvichakSockeye.RData)| Questions at the end of the lab | [Key](Labs/Week 5 fitting DLMs/HW5_answer_key.pdf) |
| 6 | Dynamic Factor Analysis |  [Lab 6 DFA](Labs/Week 6 dynamic factor analysis/Intro_to_DFA.html) | Questions at the end of the lab | [Key](Labs/Week 6 dynamic factor analysis/HW6_answer_key.pdf) |
| 7 | Fitting models with STAN |  [Lab 7 STAN](Labs/Week 7 models in Stan/Lab_7 Fitting models with Stan.html) | No HW |  |