---
title: "Lecture videos"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Winter Quarter 2017 Webcast of the lectures

Just before lecture, about 1:30pm PST on Tues and Thurs, we'll post the link to the webcast of the lecture.

### Recordings of lectures

**Lecture 1 Introduction to time-series Analysis**: <a href="https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=6ab5e7b9-38a0-4e16-ac16-95e255658ea6">Recording 1</a> (poor video, good audio), <a href="https://youtu.be/GFMo4H34o0s">Recording 2</a> (good video, poor audio).

**Lecture 2 Covariance and correlation**: <a href="https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=b965709d-2e58-4a10-8c23-ca7ef372ae39">Recording 1</a> (poor video, good audio) starts at about slide 5, <a href="https://youtu.be/ywhpS44BWdc">Recording 2</a> (good video, no audio).

<a href="https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a8e65e57-532a-4514-9599-72735b282e11">Lab 1&nbsp;Linear regression models in matrix form</a></strong>

<a href="https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=49fe74b8-3568-4152-b878-b46a807786bb"><strong>Lecture 3&nbsp;Stationary &amp; nonstationary models</strong> </a>

<a href="https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=6a689fe2-abad-4927-a011-8fbf4c1bca72"><strong>Lecture 4&nbsp;Estimation &amp; forecasting</strong></a>

<a href="https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c0512161-c77d-49d3-ab93-73ec08f63d35">Lab 2&nbsp;Intro to time series in R</a>&nbsp; (just the introduction)

<strong>Lecture 5 Intro to univariate state-space models (no video yet)</strong>

<a href="https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=228ba8b7-c647-4ea9-b14a-2122ba6fd0cc"><strong>Lecture 6&nbsp;Intro to multivariate state-space models</strong></a>

<a href="https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=7580dd9d-74f5-4f01-9c28-90f739bb905a"><strong>Lecture 7&nbsp;MARSS models with covariates</strong></a>

